name: Build
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 15 ]
        include:
          - java: 8
            profile: default
          - java: 11
            profile: jdk11
          - java: 15
            profile: jdk15
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: java -version
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -P ${{ matrix.profile }} verify
